apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "minecraft-test-1"
  namespace: "minecraft"
  labels:
    app: "minecraft-test-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "minecraft-test-1"
  template:
    metadata:
      labels:
        app: "minecraft-test-1"
    spec:
      containers:
      - name: "minecraft"
        image: "us.gcr.io/kubeoperatorstest/minecraft:v1.13.2"
        volumeMounts:
        - mountPath: "/server-data"
          name: minecraft-storage
      volumes:
      - name: minecraft-storage
        persistentVolumeClaim:
          claimName: minecraft-pvc
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
